{{- if eq .Values.mode "full" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-debezium
  labels:
    app: {{ .Release.Name }}-debezium
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9404"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      name: http
    - port: 1099
      targetPort: jmx
      name: jmx
    - port: 9404
      targetPort: metrics
      name: metrics
  selector:
    app: {{ .Release.Name }}-debezium
{{- end }}
