{{- if .Values.fileWriter.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-file-writer-output
  labels:
    app: {{ .Release.Name }}-file-writer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.fileWriter.persistence.size }}
  {{- if .Values.fileWriter.persistence.storageClass }}
  storageClassName: {{ .Values.fileWriter.persistence.storageClass }}
  {{- end }}
{{- end }}
