{{- if and (eq .Values.mode "full") .Values.metrics.kafkaExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka-exporter
  labels:
    app: {{ .Release.Name }}-kafka-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9308
      targetPort: metrics
      name: metrics
  selector:
    app: {{ .Release.Name }}-kafka-exporter
{{- end }}
