{{- if eq .Values.mode "full" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka
  labels:
    app: {{ .Release.Name }}-kafka
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: kafka
      name: kafka
    - port: 9093
      targetPort: controller
      name: controller
  selector:
    app: {{ .Release.Name }}-kafka
{{- end }}
