{{- if and (eq .Values.mode "full") .Values.metrics.kafkaExporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kafka-exporter
  labels:
    app: {{ .Release.Name }}-kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kafka-exporter
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-kafka-exporter
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z {{ .Release.Name }}-kafka 9092; do echo waiting for kafka; sleep 5; done']
      containers:
        - name: kafka-exporter
          image: "{{ .Values.metrics.kafkaExporter.image.repository }}:{{ .Values.metrics.kafkaExporter.image.tag }}"
          imagePullPolicy: {{ .Values.metrics.kafkaExporter.image.pullPolicy }}
          args:
            - --kafka.server={{ .Release.Name }}-kafka:9092
          ports:
            - containerPort: 9308
              name: metrics
{{- end }}
