apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-oracle-exporter
  labels:
    app: {{ .Release.Name }}-oracle-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9161
      targetPort: metrics
      name: metrics
  selector:
    app: {{ .Release.Name }}-oracle-exporter
