apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-oracle-secret
  labels:
    app: {{ .Release.Name }}-oracle
type: Opaque
data:
  oracle-password: {{ .Values.oracle.password | b64enc | quote }}
