global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'debezium-jmx'
    static_configs:
      - targets: ['jmx-exporter:9404']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'oracle'
    static_configs:
      - targets: ['oracle-exporter:9161']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'openlogreplicator'
    static_configs:
      - targets: ['olr:9161']
